version: "3"

services:
  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/appdata/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/appdata/data:/data
      - $PWD/appdata/config:/config
      - $PWD/appdata/logs:/var/log/caddy

  chopshop_signin:
    container_name: chopshop_signin
    image: 166first/signinwebapp:latest
    depends_on:
      - postgres
    ports:
      - "8100:8100/tcp"
    # Volumes store your data between container upgrades
    volumes:
      - './appdata:/appdata'
    restart: unless-stopped
    environment:
      - FLASK_SECRET_KEY
      - CSSIGNIN_CONFIG=/appdata/cssignin.yaml
      - LANG=en_US.UTF-8

  postgres:
    container_name: chopshop_db
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - ./appdata/db:/var/lib/postgresql/data
