[project]
name = "signinapp"
version = "1.5.5"
description = "A tool to track your team's hours during the season, using QR codes that can be quickly scanned as team members come and go."
authors = [
    { name = "Matt Soucy", email = "first@msoucy.me" },
    { name = "Ben Beauregard", email = "bot190@gmail.com" },
]
requires-python = ">=3.11, <4"
readme = "README.md"
license = "MIT"
dependencies = [
    "bootstrap-flask>=2.5.0,<2.6.0",
    "cssmin>=0.2.0,<0.3.0",
    "email-validator>=2.3.0,<2.4.0",
    "flask>=3.1.0,<3.2.0",
    "flask-admin>=2.0.0,<2.1.0",
    "flask-apscheduler>=1.13.0,<1.14.0",
    "flask-assets>=2.0,<3.0",
    "flask-excel>=0.0.7,<0.1.0",
    "flask-login>=0.6.2,<0.7.0",
    "flask-migrate>=4.1.0,<4.2.0",
    "flask-wtf>=1.2.0,<1.3.0",
    "get-docker-secret>=2.0.0,<2.1.0",
    "gunicorn>=25.3.0,<26.1.0",
    "libsass>=0.21,<1.0",
    "markupsafe>=3.0.0,<3.1.0",
    "pysass>=0.1.0,<0.2.0",
    "python-dateutil>=2.9.0,<2.10.0",
    "pytz>=2026.1,<2027.0",
    "pyyaml>=6.0,<7.0",
    "regex>=2026.4.4,<2027.1.1",
    "psycopg2-binary>=2.9.7,<2.10.0",
    "requests>=2.33.1,<2.34.0",
    "six>=1.17.0,<1.18.0",
    "sqlalchemy>=2.0.0,<2.1.0",
    "toml>=0.10.2,<0.11.0",
    "tomli>=2.4.1,<2.5.0",
    "tzdata>=2026.1,<2027.0",
    "tzlocal>=5.3.0,<5.4.0",
    "webassets>=3.0,<3.1",
    "wtforms>=3.2.1,<3.3.0",
    "flask-sqlalchemy-lite>=0.2.1",
    "types-wtforms>=3.2.1.20250809",
    "types-requests>=2.32.4.20260107",
]

[project.urls]
Repository = "https://github.com/chopshop-166/SignInWebApp"

[dependency-groups]
dev = ["ruff>=0.15.3,<0.16"]

[tool.hatch.build.targets.sdist]
include = ["signinapp"]

[tool.hatch.build.targets.wheel]
include = ["signinapp"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".eggs",
    ".git",
    ".git-rewrite",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

# Same as Black.
line-length = 100
indent-width = 4

target-version = "py313"

[tool.ruff.lint]
select = [
  # pycodestyle
  "E",
  # Pyflakes
  "F",
  # isort
  "I",
  # pyupgrade
  "UP",
  # bugbear
  "B",
  # Enable detection of banned imports
  "TID251",
]
ignore = []

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

docstring-code-format = true

# Set the line length limit used when formatting code snippets in
# docstrings.
# enabled.
docstring-code-line-length = "dynamic"
