"""SQLAlchemy 2.0

Revision ID: 235dba32858b
Revises: 7a297468f586
Create Date: 2023-01-26 23:01:44.635683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "235dba32858b"
down_revision = "7a297468f586"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("active", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("event_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column(
            "start",
            existing_type=sa.DATETIME(),
            nullable=False,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )

    with op.batch_alter_table("badge_awards", schema=None) as batch_op:
        batch_op.alter_column(
            "received",
            existing_type=sa.DATETIME(),
            nullable=False,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )

    with op.batch_alter_table("badges", schema=None) as batch_op:
        batch_op.alter_column("color", existing_type=sa.VARCHAR(), nullable=False)

    with op.batch_alter_table("event_types", schema=None) as batch_op:
        batch_op.alter_column("name", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("description", existing_type=sa.VARCHAR(), nullable=False)

    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.alter_column("name", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("description", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("code", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("location", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("type_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column(
            "registration_open",
            existing_type=sa.BOOLEAN(),
            nullable=False,
            existing_server_default=sa.text("'false'"),
        )

    with op.batch_alter_table("guardians", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column(
            "contact_order", existing_type=sa.INTEGER(), nullable=False
        )

    with op.batch_alter_table("stamps", schema=None) as batch_op:
        batch_op.alter_column(
            "user_id", existing_type=sa.VARCHAR(), type_=sa.Integer(), nullable=False
        )
        batch_op.alter_column("event_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("start", existing_type=sa.DATETIME(), nullable=False)
        batch_op.alter_column(
            "end",
            existing_type=sa.DATETIME(),
            nullable=False,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )

    with op.batch_alter_table("students", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column(
            "graduation_year", existing_type=sa.INTEGER(), nullable=False
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("role_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("approved", existing_type=sa.BOOLEAN(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("approved", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column("role_id", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("students", schema=None) as batch_op:
        batch_op.alter_column(
            "graduation_year", existing_type=sa.INTEGER(), nullable=True
        )
        batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("stamps", schema=None) as batch_op:
        batch_op.alter_column(
            "end",
            existing_type=sa.DATETIME(),
            nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.alter_column("start", existing_type=sa.DATETIME(), nullable=True)
        batch_op.alter_column("event_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column(
            "user_id", existing_type=sa.Integer(), type_=sa.VARCHAR(), nullable=True
        )

    with op.batch_alter_table("guardians", schema=None) as batch_op:
        batch_op.alter_column(
            "contact_order", existing_type=sa.INTEGER(), nullable=True
        )
        batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.alter_column(
            "registration_open",
            existing_type=sa.BOOLEAN(),
            nullable=True,
            existing_server_default=sa.text("'false'"),
        )
        batch_op.alter_column("type_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("location", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("code", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("description", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("name", existing_type=sa.VARCHAR(), nullable=True)

    with op.batch_alter_table("event_types", schema=None) as batch_op:
        batch_op.alter_column("description", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column("name", existing_type=sa.VARCHAR(), nullable=True)

    with op.batch_alter_table("badges", schema=None) as batch_op:
        batch_op.alter_column("color", existing_type=sa.VARCHAR(), nullable=True)

    with op.batch_alter_table("badge_awards", schema=None) as batch_op:
        batch_op.alter_column(
            "received",
            existing_type=sa.DATETIME(),
            nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )

    with op.batch_alter_table("active", schema=None) as batch_op:
        batch_op.alter_column(
            "start",
            existing_type=sa.DATETIME(),
            nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.alter_column("event_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=True)

    # ### end Alembic commands ###
