"""Initial Migration

Revision ID: 7a297468f586
Revises: 
Create Date: 2022-12-02 22:16:52.739438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7a297468f586"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("account_types", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("receives_funds", sa.Boolean(), nullable=False, default=False)
        )

    with op.batch_alter_table("badges", schema=None) as batch_op:
        batch_op.add_column(sa.Column("emoji", sa.String(), nullable=True))

    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("registration_open", sa.Boolean(), nullable=True, default=False)
        )
        batch_op.add_column(sa.Column("funds", sa.Integer(), nullable=False, default=0))
        batch_op.add_column(sa.Column("cost", sa.Integer(), nullable=False, default=0))
        batch_op.add_column(
            sa.Column("overhead", sa.Float(), nullable=False, default=0.5)
        )
        batch_op.alter_column("start", existing_type=sa.DATETIME(), nullable=False)
        batch_op.alter_column("end", existing_type=sa.DATETIME(), nullable=False)
        batch_op.drop_column("enabled")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.add_column(sa.Column("enabled", sa.BOOLEAN(), nullable=False))
        batch_op.alter_column("end", existing_type=sa.DATETIME(), nullable=True)
        batch_op.alter_column("start", existing_type=sa.DATETIME(), nullable=True)
        batch_op.drop_column("overhead")
        batch_op.drop_column("cost")
        batch_op.drop_column("funds")
        batch_op.drop_column("registration_open")

    with op.batch_alter_table("badges", schema=None) as batch_op:
        batch_op.drop_column("emoji")

    with op.batch_alter_table("account_types", schema=None) as batch_op:
        batch_op.drop_column("receives_funds")

    # ### end Alembic commands ###
