"""Email as signin part 2

Revision ID: 7bafa58010d4
Revises: 073aa9bc98d2
Create Date: 2023-09-16 12:28:33.578066

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "7bafa58010d4"
down_revision = "073aa9bc98d2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f("uq_events_code"), ["code"])

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f("uq_users_code"), ["code"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_users_code"), type_="unique")

    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_events_code"), type_="unique")

    # ### end Alembic commands ###
