"""Pronouns

Revision ID: 9b0e597da71c
Revises: 7bafa58010d4
Create Date: 2023-09-16 12:34:12.079018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b0e597da71c'
down_revision = '7bafa58010d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pronouns', sa.Enum('He_Him', 'She_Her', 'They_Them', 'He_They', 'She_They', name='pronoun'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('pronouns')

    # ### end Alembic commands ###
